### PR TITLE
fix: consistently format units in reference ranges

### LINKED ISSUE #103: BUG: Fix units display on lab ref ranges
## Description

Please update how units are displayed for lab reference ranges. If the unit is `%`, we want no visible space between the value and the % -- `<value>%`. For all other cases, units should be separated from the value by a space like `<value> <unit>`.

To do this, we have to change the FHIR path for `observationRefRange`.  Currently, we pull all the reference range values from the `text` field. If the `low` and `high` value and unit fields exist under `referenceRange`, we should pull from them instead. 

## Steps to reproduce

`10e5b07b-5d3f-426f-a7e1-13ea909ff5a5`: [Link to eCR Viewer](http://localhost:3000/view-data?id=32#lab-results-from-mercy-campus-muskegon-mi-mcmu-hospital-lab)

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority
- [x] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

No FHIR conversion should be required for this ticket.

### PR DESCRIPTION
**Pull request by mcmcgrath13**
# PULL REQUEST

## Summary

Format observation reference ranges consistent with other quantities (when low/high available)

## Related Issue

Fixes #103

### CODE REVIEW

File: containers/ecr-viewer/src/app/services/formatService.ts [hunk 1]
```diff
@@ -325,6 +327,51 @@ export const formatCodeableConcept = (
...
+ * @returns formatted string
+ */
+export const formatRange = (data: Range | undefined): string | undefined => {
+  if (!data) return;
+  const low = formatQuantity(data.low);
+  const high = formatQuantity(data.high);
+  if (low && high) {
+    return `${low} - ${high}`;
+  } else if (low) {
+    return `>=${low}`;
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/services/formatService.ts:369]: Could `<low>` and `<high>` also apply to dates, and if so, does the `>=` and `<=` make sense in that case?

Though, I saw that this is currently only applied to Observation ref ranges. I would maybe make a note about this so that it won't accidentally get applied to dates in the future?

File: containers/ecr-viewer/src/app/services/formatService.ts [hunk 2]
```diff
@@ -325,6 +327,51 @@ export const formatCodeableConcept = (
   return undefined;
 };
 
+// Map from computer to human readable units
+const UNIT_MAP = new Map([
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/services/formatService.ts:331]: Just curious why you moved this from `utils` to `formatService`?

File: containers/ecr-viewer/src/app/services/formatService.ts (hunk 1 above)
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/services/formatService.ts:369]: `Range` is defined using `Quantities`, so we shouldn't run into this with dates as that would use a `Period` (pretty sure)

**Review by angelathe — APPROVED** [review]
💯
