### PR TITLE
bug: Do not show relevant lab results and clinical data section in Condition summary if no data

### LINKED ISSUE #1012: eCR Summary - When “relevant labs and clinical info” is empty, do not show those fields.
## Description

When there is no clinical information OR labs relevant to the eCR, remove those sections from the summary. 

When we were in TN for the onsite, the eCR coordinator specified that epis may write off eCRs if clinical information or lab information specifies that there is no information.

## Steps to reproduce

1. Open an eCR 
2. Look at the individual 

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority

- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [X] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

### PR DESCRIPTION
**Pull request by JNygaard-Skylight**
# PULL REQUEST

## Summary

If a condition does not have clinical data, lab reports, or immunizations do not include it in the summary.

## Related Issue

Fixes #1012 

## Old
image

## New
image

### CODE REVIEW

**Comment by mcmcgrath13** [comment]
I read the ticket differently. That the conditions should always be there, but if there are no labs or problems or whatever, then remove that line item from the drop down. @ashton-skylight could you clarify?

**Comment by JNygaard-Skylight** [comment]
> I read the ticket differently. That the conditions should always be there, but if there are no labs or problems or whatever, then remove that line item from the drop down. @ashton-skylight could you clarify?

Sorry, reread the ticket, I see what we want to do. When a section is empty, we want to just not display it instead of displaying "No matching...".

File: containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx [hunk 1]
```diff
@@ -51,35 +53,49 @@ const EcrSummary: React.FC<EcrSummaryProps> = ({
...
-              className="text-bold margin-0 margin-bottom-1"
-              id="relevant-labs"
-            >
-              Lab Results Relevant to Reportable Condition
-            </h5>
-            <div className="margin-top-0">
-              {condition.labDetails.map((item, index) => (
-                <DataTableDisplay item={item} key={`${item.title}-${index}`} />
+            {hasImmunizationDetails ||
+              (hasClinicalDetails && (
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx:57]: Why place the `(` before `hasClinicalDetails`?

**Comment by JNygaard-Skylight** [comment]
> @mcmcgrath13 @JNygaard-Skylight Might've interpreted this differently, but I thought @ashton-skylight said that the whole section should be removed? Out of worry that folks might not actually open the accordion to see that there are no relevant clinical data/labs for that condition
> 
> But your work matches the expected result so 🤷‍♀️

This was also my assumption, but see @mcmcgrath13's comment. I'm now pretty unsure of myself, so I'll wait until Ashton has a look.

**Comment by mcmcgrath13** [comment]
> > @mcmcgrath13 @JNygaard-Skylight Might've interpreted this differently, but I thought @ashton-skylight said that the whole section should be removed? Out of worry that folks might not actually open the accordion to see that there are no relevant clinical data/labs for that condition
> > But your work matches the expected result so 🤷‍♀️
> 
> This was also my assumption, but see @mcmcgrath13's comment. I'm now pretty unsure of myself, so I'll wait until Ashton has a look.

I pinged @ashton-skylight to weigh in here 😅 

I thought the concern was that if people opened the accordion and so no relevant clinical info was found, they'd take that as base truth and not go look around the eCR for more details. So we didn't want to assert there's no info, but still want to highlight that this was a condition on the eCR

File: containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx (hunk 1 above)
Comment (JNygaard-Skylight) [reply containers/ecr-viewer/src/app/view-data/components/EcrSummary.tsx:57]: I do not need those brackets, but I do added brackets around the or statement. That will also fix the snapshot.

**Review by angelathe — APPROVED** [review]
🎉🎉
