### PR TITLE
fix: eRSD Warnings

### LINKED ISSUE #496: eSRD warning has hardcoded data that does not match content in RR
## Description

When getting an outdated/unknown version eRSD warning, we are currently hardcoding the messages, but these do not always match the actual data we see in the RRs

## Steps to reproduce

hardcoded messages:
Image

acutal messages:
Image

## Expected Result

_Explain how it should function if the bug was fixed. Attach screenshot if applicable_

## Actual result

The warning should derive its data from the content of the RR as much as possible instead of hardcoding based on error code

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority

- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [x] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

### PR DESCRIPTION
**Pull request by angelathe**
# PULL REQUEST

## Summary

- Remove the hardcoding of the eRSD warnings.
  - If the warning reason is given, then it will use what's given. If a warning code but no reason is given, it will use the preferred concept names from the PHIN value sets (see links below).
  - For Version in Use, if the name of the detail exists, I add it to the table (ex. "Outdated eRSD Version Detail")
- Add utils for eICR Processing Status/Reason/Details
- Modify unit tests & bundle test fixtures that had the incorrect FHIR conversion of eRSD warnings
- Modify other test fixtures in `ingestion` and the `TCR`
- Modify FHIR paths of eICR Processing Status in `message-parser`

## Related Issue

Fixes #496 

## Acceptance Criteria

- [ ] The warning should derive its data from the content of the RR as much as possible instead of hardcoding based on error code
- [ ] The corner case handling in utils/evaluate.ts should be removed

## Screenshots
3.1 Sample eCR
Screenshot 2025-04-18 at 13 00 56

eCR with no Processing Warnings
Screenshot 2025-04-18 at 13 01 05

eCR with only partial eRSD Warnings data
Screenshot 2025-04-17 at 19 20 03

eCR processed with warning/error, but no reason/details
Screenshot 2025-04-24 at 15 44 34

## Additional Information

Related FHIR Converter ticket: https://github.com/CDCgov/dibbs-FHIR-Converter/pull/9

**Note about the suggested solutions**: These are meant to be hard-coded. Currently, we only have suggested solutions for two of the warning reasons. Per Emma, for each warning reason, use the suggested solutions we have, leave the others blank and write "no suggested solution found", and in the long-term we'll chat with APHL to see if these do come with a suggested solution we can use, or if we'll have to make up the language.

**Link to RR Spec (see Vol 2)**
https://www.hl7.org/implement/standards/product_brief.cfm?product_id=470

**Value Set Links**
- [eICR Processing Status](https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.113883.10.20.15.2.5.8)
- [eICR Processing Status Reason](https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.113883.10.20.15.2.5.7)
- [eICR Processing Status Reason Details](https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.113883.10.20.15.2.5.10)

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

### CODE REVIEW

File: containers/fhir-converter/Dockerfile [hunk 1]
```diff
@@ -1,7 +1,8 @@
 FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
 
 # Download FHIR-Converter
-RUN git clone https://github.com/CDCgov/dibbs-FHIR-Converter.git --branch v7.0-2 --depth 1 /build/FHIR-Converter
+# TODO ANGELA: Remove #496
+RUN git clone https://github.com/CDCgov/dibbs-FHIR-Converter.git --branch angela/461-bug-eicr-processing --depth 1 /build/FHIR-Converter
```
Comment (angelathe) [inline containers/fhir-converter/Dockerfile:5]: TODO: Need to remove this change before merging

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 2]
```diff
@@ -96,35 +101,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
-        suggestedSolution:
-          "The trigger code version your organization is using is out-of-date. Please have your EHR administration install the current version for complete eCR functioning.",
-      });
-    }
-  }
+  const eRSDTextList: ERSDWarning[] =
+    fhirEICRProcessingStatus &&
+    fhirEICRProcessingStatus !== "RRVS19" &&
+    fhirEICRProcessingStatusReasonObs
+      ? (() => {
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:117]: why do this in a function that we call immediately? also it seems like we only ever return one ERSD warning, but are gathering it into an array, which feels a bit off - is that the intention?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 3]
```diff
@@ -96,35 +101,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+              const detailVal = component.valueString;
+              const detailCode = component.code?.coding?.[0]?.code;
+              const detailDisplay = component.code?.coding?.[0]?.display;
+
+              if (!detailCode) return;
+
+              if (
+                ReasonDetailMap[warningCode as keyof typeof ReasonDetailMap] ===
+                detailCode
+              ) {
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:138]: it's not obvious to me what the `ReasonDetailMap` is doing here - is it a filter for warnings that have a detail? if so, what about naming it a bit more verbosely and instead storing that as an array and using `includes` instead of the map lookup?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 4]
```diff
@@ -96,35 +101,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+                versionExpected = detailVal;
+              }
+            },
+          );
+
+          return warningName || versionUsed || versionExpected || warningCode
+            ? [
+                {
+                  warning: warningName,
+                  versionUsed: versionUsed ?? "No data",
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:152]: should these be the stylized `No Data` to match? if not, should they instead be undefined/optional?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 3 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:138]: This check might not be totally necessary. Essentially, if the warning reason was "Outdated Version" and it had a detail, I wanted to make sure that the detail type matched, i.e. "Outdated Version Detail" and not "Inactive" or "Malformed Version Detail".

https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.113883.10.20.15.2.5.10

All the details except for `RRVS33` describe the current version used though. Might actually be preferrable not to add this check and display whatever is given to us, as long as the type of detail we receive is displayed. Thoughts?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 2 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:117]: Missed updating this from the previous iteration of how we stored eRSD Warnings, will change! If we're following the spec, this should not be an array.

File: containers/ecr-viewer/src/app/tests/services/ecrMetadataService.test.ts [hunk 5]
```diff
@@ -92,15 +93,20 @@ describe("Evaluate Ecr Metadata", () => {
...
+        versionUsed: "Outdated eRSD (RCTC) Version Detail: 3/29/2022",
         expectedVersion:
-          "Sending organization should be using one of the following: 2023-10-06, 1.2.2.0, 3.x.x.x.",
+          'The expected eRSD (RCTC) version should be one of the following: ["2024-06-28","1.2.4.0","3.x.x","2024-04-05"] ',
         suggestedSolution:
           "The trigger code version your organization is using is out-of-date. Please have your EHR administration install the current version for complete eCR functioning.",
       },
     ]);
   });
+  it("if processed with no warnings, should have empty eRSDwarnings", () => {
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/tests/services/ecrMetadataService.test.ts:105]: can we add a test for one of the warnings that doesn't have a suggested solution or version related to it?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 3 above)
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:138]: I'd lean towards display whatever is given to us

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 2 above)
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:117]: It has a bit of a weird code smell to me that we have a large inline thunk that we call immediately (plus makes the else branch of the ternary very far away). Maybe pull out the function to a proper function?

File: containers/ecr-viewer/src/app/view-data/components/EcrDocument/accordion-items.tsx [hunk 6]
```diff
@@ -194,13 +193,13 @@ export const getEcrDocumentAccordionItems = (
               clinicalNotesData={clinicalData.clinicalNotes.unavailableData}
               ecrMetadataUnavailableData={[
                 ...ecrMetadata.eicrDetails.unavailableData,
-                ...(ecrMetadata.eRSDWarnings.length === 0
+                ...(Object.keys(ecrMetadata.eRSDWarnings).length === 0
```
[the remark this answers is not in the document]
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/view-data/components/EcrDocument/accordion-items.tsx:196]: I lean towards 3 for consistency and ctrl-f-ability

File: containers/ecr-viewer/src/app/tests/services/ecrMetadataService.test.ts (hunk 5 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/tests/services/ecrMetadataService.test.ts:105]: Done!

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 2 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts]: Ah yes, you're right that does make it hard to read/follow. Made a change

File: containers/ecr-viewer/src/app/view-data/components/EcrDocument/accordion-items.tsx (hunk 6 above)
[the remark this answers is not in the document]
Comment (ashton-skylight) [reply containers/ecr-viewer/src/app/view-data/components/EcrDocument/accordion-items.tsx:196]: Agree with 3. Not sure how much knowledge users will have regarding where there are or are not the eRSD warnings. We could include a tooltip, something along the lines of "When an eCR is successfully processed, there are no eRSD warnings"

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 7]
```diff
@@ -40,10 +40,10 @@ interface EcrMetadata {
 }
 
 export interface ERSDWarning {
-  warning?: string;
-  versionUsed?: string;
-  versionExpected?: string;
-  suggestedSolution?: string;
+  warning?: string | JSX.Element;
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:42]: maybe have these all be `ReactNode` or `RenderableNode` instead?

Comment (angelathe) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:42]: Yes! Made that change already in a commit I haven't pushed up yet oops

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 8]
```diff
@@ -96,36 +106,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+
+    const coding = reasonObs.valueCodeableConcept?.coding?.[0];
+    const warningCode = coding?.code;
+    const warningName =
+      coding?.display || eicrProcessingReasonMap[warningCode ?? ""] || "";
+
+    let versionUsed: string | undefined;
+    let versionExpected: string | undefined;
+
+    (reasonObs.component ?? []).forEach((component) => {
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:136]:
```suggestion
    reasonObs.component?.forEach((component) => {
```

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 9]
```diff
@@ -96,36 +106,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+      } else {
+        versionUsed = detailDisplay
+          ? `${detailDisplay}: ${detailVal}`
+          : detailVal;
+      }
+    });
+    return warningName || versionUsed || versionExpected || warningCode
+      ? {
+          warning: warningName ?? noData,
+          versionUsed: versionUsed ? versionUsed : noData,
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:154]:
```suggestion
          versionUsed: versionUsed || noData,
```

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 10]
```diff
@@ -96,36 +106,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+          versionExpected: versionExpected ? versionExpected : noData,
+          suggestedSolution:
+            ersdWarningsSuggestedSolutionsMap[warningCode ?? ""] ?? noData,
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:157]:
```suggestion
            ersdWarningsSuggestedSolutionsMap?.[warningCode] ?? noData,
```

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 11]
```diff
@@ -96,36 +106,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+    if (processingStatus === "RRVS19") {
+      return eICRProcessingSuccessMsg;
+    } else if (!processingStatus || !reasonObs) {
+      return {};
     }
+
+    const coding = reasonObs.valueCodeableConcept?.coding?.[0];
+    const warningCode = coding?.code;
+    const warningName =
+      coding?.display || eicrProcessingReasonMap[warningCode ?? ""] || "";
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:131]:
```suggestion
      coding?.display || eicrProcessingReasonMap?.[warningCode] || "";
```

I _think_ this is valid syntax 🤞

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 12]
```diff
@@ -96,36 +106,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
-      eRSDTextList.push({
-        warning:
-          "Sending organization is using an outdated eRSD (RCTC) version",
-        versionUsed: "2020-06-23",
-        expectedVersion:
-          "Sending organization should be using one of the following: 2023-10-06, 1.2.2.0, 3.x.x.x.",
-        suggestedSolution:
-          "The trigger code version your organization is using is out-of-date. Please have your EHR administration install the current version for complete eCR functioning.",
-      });
+  function geteRSDTextList(
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:118]: this name feels outdated with the code (this is not a list of text as I read it)

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 13]
```diff
@@ -96,36 +106,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+          warning: warningName ?? noData,
+          versionUsed: versionUsed ? versionUsed : noData,
+          versionExpected: versionExpected ? versionExpected : noData,
+          suggestedSolution:
+            ersdWarningsSuggestedSolutionsMap[warningCode ?? ""] ?? noData,
+        }
+      : {};
   }
 
+  const eRSDTextList: ERSDWarning | JSX.Element = geteRSDTextList(
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:162]: and similarly this is not a list anymore

File: containers/ecr-viewer/src/app/tests/components/EcrMetadata.test.tsx [hunk 14]
```diff
@@ -42,16 +42,14 @@ const eicrDetails: DisplayDataProps[] = [
...
-  {
-    warning: "Sending organization is using an malformed eRSD (RCTC) version",
-    versionUsed: "2020-06-23",
-    expectedVersion:
-      "Sending organization should be using one of the following: 2023-10-06, 1.2.2.0, 3.x.x.x.",
-    suggestedSolution:
-      "The trigger code version your organization is using could not be determined. The trigger codes may be out date. Please have your EHR administrators update the version format for complete eCR functioning.",
-  },
-];
+const eRSDWarnings: ERSDWarning = {
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/tests/components/EcrMetadata.test.tsx:45]: in a lot of places we still have the pluralized `eRSDWarnings`, but it seems like with the current logic we only ever get one. Should we update the pluralization? or are we missing something where it's possible to have multiple warnings?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 15]
```diff
@@ -96,36 +106,64 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
-        suggestedSolution:
-          "The trigger code version your organization is using is out-of-date. Please have your EHR administration install the current version for complete eCR functioning.",
-      });
+  function geteRSDTextList(
+    processingStatus: string | undefined,
+    reasonObs: Observation | undefined,
+  ): ERSDWarning | JSX.Element {
+    if (processingStatus === "RRVS19") {
+      return eICRProcessingSuccessMsg;
+    } else if (!processingStatus || !reasonObs) {
```
[the remark this answers is not in the document]
Comment (angelathe) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:124]: I used `||` because I think it's okay to have a status and not a reason, since the status could be a successful process

Screenshot 2025-04-24 at 10 49 20

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 11 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:131]: Hmmm typescript got mad at me, I think bc it's the possibility that `warningCode` might be undefined? Changed it to:
```
    const warningCode = coding?.code ?? "";
    const warningName =
      coding?.display || eicrProcessingReasonMap[warningCode] || "";

```

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 8 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:136]: Same comment as above, changed to:
```
    const warningDetails = reasonObs.component ?? [];
    warningDetails.forEach((component) => {
    ....
```

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:124]: but the nots I think this is saying `if we don't have a status or we don't have a reason, bail out` (so no reason, but yes status would bail out), but I think you want to say `if we don't have a status and we don't have a reason, bail out`

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 8 above)
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:136]: given that this is a `forEach` the default [] should land us in the same spot as the `?.`. Why prefer the former?

File: containers/ecr-viewer/src/app/tests/components/EcrMetadata.test.tsx (hunk 14 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/tests/components/EcrMetadata.test.tsx:45]: No you're right! Updating language now

File: containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx [hunk 16]
```diff
@@ -17,12 +17,12 @@ import { ToolTipElement } from "./ToolTipElement";
...
-  eRSDWarnings: ERSDWarning | JSX.Element;
+  eRSDWarning: ERSDWarning | JSX.Element;
   eCRCustodianDetails: DisplayDataProps[];
   eicrAuthorDetails: DisplayDataProps[][];
 }
 
-const eRSDWarningsTooltip = (
+const eRSDWarningTooltip = (
   <ToolTipElement toolTip="Can be used to help you identify healthcare providers that need to update their eRSD (Electronic Reporting and Surveillance Distribution) version.">
     eRSD Warnings
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:27]: @angelathe @ashton-skylight given there can only be one warning, should we update the name of this field? and sometimes the warnings is (yay! it's all good) - maybe `eRSD Processing Info` ? or similar?

Comment (angelathe) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:27]: @mcmcgrath13 That works for me, though maybe `Info` is a bit general. `eRSDProcessingTooltip`?

Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:27]: sorry, I mean the title we display as the field's name, not so much the variable name (though maybe that too if we change the field name on line 27)

File: containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx [hunk 17]
```diff
@@ -54,12 +54,12 @@ const EcrMetadata = ({
       <AccordionSubSection title="RR Details">
         <ReportabilitySummary rrDetails={rrDetails} />
         <div className="section__line_gray" />
-        {React.isValidElement(eRSDWarning) ? (
+        {!eRSDWarning ? (
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:57]: is missingness definitely indicative of success here?

Comment (angelathe) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:57]: I think it makes sense for `eRSDWarning` to be "undefined" if the eCR was processed successfully, unless you have other thoughts?
Can also make this more explicit by checking `eRSDWarning === undefined`

Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:57]: I can definitely see a world where that makes sense, I can also see a world where the processing is so messed up that we don't get any status because it's broken, so I'm a little hesitant to read into it deeply.

Maybe set up the data structure like

```
interface eRSDWarning { same as already exists}
interface eRSDInfo {
   success: boolean;
   warning?: eRSDWarning;
}
```

then we leave it undefined if there's no info at all, but can use the `success` field to indicate the 👍 status or the 👎 status and then warning info if we have that as well

Comment (angelathe) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx]: Sorry @mcmcgrath13! Forgot to merge my edits (✈️ work). Made the changes below + some more renaming nits

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 18]
```diff
@@ -96,36 +110,77 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+        eRSDWarning: {
+          warning: "eICR processed with a warning or error (unknown)",
+          versionUsed: noData,
+          versionExpected: noData,
+          suggestedSolution: noData,
+        },
+      };
+    } else if (!processingStatus && !reasonObs) {
+      return { success: false };
     }
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:140]: should this one be undefined? we don't know anything at this point, so have no data

File: containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx [hunk 19]
```diff
@@ -44,46 +54,51 @@ const EcrMetadata = ({
...
-                      <td className="padding-105">
-                        {warningItem.suggestedSolution}
-                      </td>
-                    </tr>
-                  ))}
-              </tbody>
-            </Table>
-            <div className="section__line_gray"></div>
+            <div className="header-data-title">{eRSDWarningTooltip}</div>
+            {eICRProcessingSuccessMsg}
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:60]: can we inline this now that it's used locally instead of exported?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 20]
```diff
@@ -123,20 +123,22 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
   ): ERSDInfo {
+    const unknownWarning: ERSDInfo = {
+      success: false,
+      eRSDWarning: {
+        warning: "eICR processed with a warning or error (unknown)",
+        versionUsed: noData,
+        versionExpected: noData,
+        suggestedSolution: noData,
+      },
+    };
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:134]: pull this out to a more global const?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 21]
```diff
@@ -44,7 +44,7 @@ interface EcrMetadata {
 }
 
 export interface ERSDInfo {
-  success: boolean;
+  success: boolean | undefined;
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:47]: I think this should be boolean, but the field `eRSDInfo?: ERSDInfo` so the `geteRSDInfo` would return `ERSDInfo | undefined`

**Comment by akasper** [comment]
Ran into some trouble seeding data, but overall code looks good!

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 22]
```diff
@@ -96,36 +120,69 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+        versionUsed = detailDisplay
+          ? `${detailDisplay}: ${detailVal}`
+          : detailVal;
+      }
+    });
+    return warningName || versionUsed || versionExpected || warningCode
+      ? {
+          success: false,
+          eRSDWarning: {
+            warning: warningName ?? noData,
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:171]: why `??` here instead of `||` - same question for `suggestedSolution`

File: containers/ecr-viewer/src/app/view-data/components/EcrDocument/accordion-items.tsx [hunk 23]
```diff
@@ -146,7 +148,9 @@ export const getEcrDocumentAccordionItems = (
       content: (
         <>
           {Object.keys(ecrMetadata.rrDetails).length > 0 ||
-          ecrMetadata.eRSDWarnings.length > 0 ||
+          (ecrMetadata.eRSDProcessingInfo &&
+            (ecrMetadata.eRSDProcessingInfo.success ||
+              ecrMetadata.eRSDProcessingInfo.eRSDWarning)) ||
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/view-data/components/EcrDocument/accordion-items.tsx:153]: in practice, should just the first check be necessary?

File: containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx [hunk 24]
```diff
@@ -44,46 +50,52 @@ const EcrMetadata = ({
...
+                      {eRSDProcessingInfo.eRSDWarning.warning}
+                    </td>
+                    <td className="padding-105">
+                      {eRSDProcessingInfo.eRSDWarning.versionUsed}
+                    </td>
+                    <td className="padding-105">
+                      {eRSDProcessingInfo.eRSDWarning.versionExpected}
+                    </td>
+                    <td className="padding-105">
+                      {eRSDProcessingInfo.eRSDWarning.suggestedSolution}
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:90]: half-thought (feel free to ignore) - given we have this styling type code over here, does it still make sense to fill in `noData` over in the data processing side? Could we instead consolidate that here? would that make anything simpler?

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts (hunk 22 above)
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:171]: also, should we default in the unknown warning text instead of `noData` on the warning code?

File: containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx (hunk 24 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:90]: Hm, just thinking out loud -- by the time the data reaches `EcrMetadata` I saw it as already being processed/set -- I didn't view the `warningName || noData` and etc. as styling

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 25]
```diff
@@ -31,16 +40,32 @@ interface EcrMetadata {
...
+  success: boolean;
+  eRSDWarning?: ERSDWarning;
 }
 
 export interface ERSDWarning {
-  warning: string;
-  versionUsed: string;
-  expectedVersion: string;
-  suggestedSolution: string;
+  warning?: RenderableNode;
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:52]: `warning` is always populated now I think

Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts:52]: and maybe a `string`?

File: containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx (hunk 24 above)
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:90]: I do think of `noData` as more of styling than processing as it's really a display detail for how we show no data than it is a typically missing/nullish type value which it represents. It's a much bigger problem than this PR how prevalently we need to use it in the code base (typically in sub-no-data's like we have here).

Maybe part of the reason this feels like styling is it isn't using the `DataDetails`or`Table`-ish type component we usually use, but is instead constructing one directly 🤔 . Something feels slightly amiss here, but I'm having trouble placing it - could this use `BaseTable` instead of the inlined table markup?

sorry this is rambly - trying to put my finger on something subtle

Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:90]: or could the ersd info return a data display props that's been `evaluateData`'ed to do the available/unavailable split so its less special?

Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:90]: I know this has been a journey - feel free to say "go away. these can be follow ons if we want"

File: containers/ecr-viewer/src/app/services/ecrMetadataService.ts [hunk 26]
```diff
@@ -96,36 +121,69 @@ export const evaluateEcrMetadata = (fhirBundle: Bundle): EcrMetadata => {
...
+          success: false,
+          eRSDWarning: {
+            warning: warningName || unknownWarningText,
+            versionUsed: versionUsed || noData,
+            versionExpected: versionExpected || noData,
+            suggestedSolution:
+              ersdWarningSuggestedSolutionsMap[warningCode] || noData,
+          },
+        }
+      : unknownWarning;
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/services/ecrMetadataService.ts:179]: I think we end up in the same place if we only return lines 169-178 given if everything is empty, that will resolve to the same as `unknownWarning`

Comment (angelathe) [reply containers/ecr-viewer/src/app/services/ecrMetadataService.ts]: Looking at this, not sure if I actually need `warningName || versionUsed || versionExpected || warningCode` anymore either

File: containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx (hunk 24 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:90]: @mcmcgrath13 I agree! But yeah would it be alright if we made this a follow up PR? I can work on this after my other tickets that are in queue

Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:90]: yup! no worries. I think the only really outstanding question on this is now the field naming/tooltip

File: containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx (hunk 16 above)
Comment (ashton-skylight) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:27]: That sounds good @mcmcgrath13 @angelathe !

Comment (angelathe) [reply containers/ecr-viewer/src/app/view-data/components/EcrMetadata.tsx:27]: Noting here that Ashton gave the 👍  to rename the field `eRSD Processing Info`

File: containers/fhir-converter/Dockerfile (hunk 1 above)
Comment (angelathe) [reply containers/fhir-converter/Dockerfile]: Reversed change

File: containers/fhir-converter/Dockerfile [hunk 27]
```diff
@@ -1,8 +1,7 @@
 FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
 
 # Download FHIR-Converter
-# TODO ANGELA: Remove #496
-RUN git clone https://github.com/CDCgov/dibbs-FHIR-Converter.git --branch angela/461-bug-eicr-processing --depth 1 /build/FHIR-Converter
+RUN git clone https://github.com/CDCgov/dibbs-FHIR-Converter.git --branch v7.0-2 --depth 1 /build/FHIR-Converter
```
Comment (mcmcgrath13) [inline containers/fhir-converter/Dockerfile]: this still needs to be updated, right?

Comment (angelathe) [reply containers/fhir-converter/Dockerfile]: Hmmmm I reverted the change in [this commit](https://github.com/CDCgov/dibbs-ecr-viewer/commit/d9d22bef430bde283e62bb807c55065757a7b899), idk why its not showing up

File: containers/ecr-viewer/src/app/tests/services/ecrMetadataService.test.ts [hunk 28]
```diff
@@ -1,9 +1,16 @@
...
-import { evaluateEcrMetadata } from "@/app/services/ecrMetadataService";
+import BundlePatient from "../../../../../../test-data/fhir/BundlePatient.json";
+import sample_ecr from "../../../../../../test-data/fhir/sample_ecr.json";
+import {
+  evaluateEcrMetadata,
+  unknownWarning,
+} from "@/app/services/ecrMetadataService";
+import { noData } from "@/app/utils/data-utils";
 
 describe("Evaluate Ecr Metadata", () => {
```
Comment (akasper) [inline containers/ecr-viewer/src/app/tests/services/ecrMetadataService.test.ts:15]: These are looking really good. I'd like to suggest a few test cases:

* `processingStatus` is `RRVS19` (i.e. eICR processed)
  - (we expect `evaluateEcrMetadata` to return `eRSDProcessingInfo: undefined`)
* `processingStatus` is non-`RRVS19`
  - (we expect `evaluateEcrMetadata` to return `eRSDProcessingInfo`, reflecting the `unknownWarning` state)
* `processingStatus` is non-`RRVS19`, `reasonObs` exists, but `reasonObs.valueCodeableConcept` lacks a populated `coding` list
* `reasonObs` exists, but `warningCode` is unknown
  - This isn't in the map... could it be a real thing?
* `reasonObs` exists, but `component` list is missing
* `reasonObs` exists, but `component` for expected version (`RRVS33`) is missing
* `reasonObs` exists for non version used `RRVS33`
* `reasonObs` exists, but `component` has missing `valueString`
* `reasonObs` exists, but `warningCode` doesn't have a mapped suggested solution

**Review by akasper — APPROVED** [review]
From my perspective: This properly addresses the core problem documented in issue #496 . We're replacing hardcoded eRSD warning messages with logic that dynamically extracts relevant info from the FHIR RR. 

We're using a map for suggested solutions, which leaves a little room for future improvements. This is an intentional decision that is well-documented here in the PR. 

I provided some suggested test coverage solutions; those changes might best live in a separate ticket/PR.

File: containers/ecr-viewer/src/app/utils/eicr-processing-utils.ts [hunk 29]
```diff
@@ -0,0 +1,30 @@
...
+  RRVS27:
+    "eICR was processed with the severe warning of: required data not found",
+  RRVS28: "eICR was processed with the warning of: content or format issues",
+  RRVS30: "Inactive eRSD (RCTC) Code",
+  RRVS34: "Malformed eRSD (RCTC) Version",
+  RRVS29: "Outdated eRSD (RCTC) Version",
+};
+
+// Note: Only have these suggested solutions currently. Long-term, we will figure out suggested solutions for the other warning reasons with APHL
+export const ersdWarningSuggestedSolutionsMap: Record<string, string> = {
```
[the remark this answers is not in the document]
Comment (angelathe) [reply containers/ecr-viewer/src/app/utils/eicr-processing-utils.ts:25]: Hmmmm this is a great question @akasper! I appreciate all these comments. Noting all these things to address in #674
