### PR TITLE
fix: Misc notes display bug

### LINKED ISSUE #498: Misc. note failed to display
## Description

A misc. note from the 3.1 testing ecr failed to display

## Steps to reproduce

_List out the steps in detail to reproduce the bug_

1. Populate the `div` field with
```
<list styleCode=\"xTOC\" xmlns=\"urn:hl7-org:v3\"><item><caption>Assessment and Plan - JohnTESTPROVIDER Powers, MD - Mon Jan 31, 2022 3:52 PM CST</caption><content ID=\"Note2\"><content><content styleCode=\"xLabel\">Formatting of this note might be different from the original.</content><br />This patient was born with a cleft hard palate. Dr Powers requested two future office visits.</content><br /><content styleCode=\"xLabel\">Electronically signed by JohnTESTPROVIDER Powers, MD at 01/31/2022 3:53 PM CST</content><br /></content></item><item><caption>Consults - JohnTESTPROVIDER Powers, MD - Wed Apr 14, 2021 10:32 AM CDT</caption><content ID=\"Note3\"><content><content styleCode=\"xLabel\">Formatting of this note might be different from the original.</content><br />Patient should get order to see Surgery for initial consult.</content><br /><content styleCode=\"xLabel\">Electronically signed by JohnTESTPROVIDER Powers, MD at 04/14/2021 10:33 AM CDT</content><br /></content></item></list><footnote ID=\"subTitle1\" styleCode=\"xSectionSubTitle\" xmlns=\"urn:hl7-org:v3\">documented in this encounter</footnote>
```

## Expected Result

The misc. note should display in the clinical info

## Actual result

Image

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority

- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [x] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

This is coming through FHIR conversion, but not showing in the Viewer.

### PR DESCRIPTION
**Pull request by angelathe**
# PULL REQUEST

## Summary

- Add check for no tables in `formatTablesToJson`

## Related Issue

Fixes #498 

## Acceptance Criteria

Please copy the acceptance criteria from your ticket and paste it here for your reviewer(s)

## Additional Information

The 3.1 sample eCR has malformed HTML for their Misc Notes, so the notes display but we still get errors. Made the decision not to address this (at least until we get more data and see recurring issues).

## Checklist

- [ ] Check that misc notes of the 3.1 sample eCR now displays

### CODE REVIEW

File: containers/ecr-viewer/src/app/view-data/components/EcrDocument/clinical-data.tsx [hunk 1]
```diff
@@ -252,6 +252,7 @@ export const returnCareTeamTable = (
 
 /**
  * Helper to evaluate the misc notes which can be either a string or a table.
+ * Note: Malformed HTML will result in hydration errors (but text will still display)
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/view-data/components/EcrDocument/clinical-data.tsx:255]: could you put this note on `safeParse` instead?

**Review by mcmcgrath13 — COMMENTED** [review]
could we add a test for `formatTableToJSON` that covers the shape of the data that was causing an issue?

**Comment by angelathe** [comment]
> could we add a test for `formatTableToJSON` that covers the shape of the data that was causing an issue?

@mcmcgrath13 There was already an existing test checking that we get an empty array back from `formatTablesToJSON`, but I updated the test fixture to reflect this specific case

**Review by mcmcgrath13 — APPROVED** [review]
👏
