### PR TITLE
fix: sticky header nits

### LINKED ISSUE #975: User & Program Management: Sticky header
## Description

When the user is going to either (1) create or edit a user or (2) create or edit a program area, they will eventually scroll down to customize the section. The header is currently sticky, but needs 2 changes: 

1) Keeps the arrow <-back to user management OR <-back to program management on the header sticky 
2) Adds a slight drop shadow to the header 

## Steps to reproduce

In user management 
1. click 'add user'
2. scroll down 

In program management
1. click 'add program area'
2. scroll down

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority

- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [X] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

### PR DESCRIPTION
**Pull request by angelathe**
# PULL REQUEST

_PR title: Remember to name your PR descriptively and follow [conventional commits](https://cheatsheets.zip/conventional-commits)!_

## Summary

- Add back button to sticky header
- Reduce vertical space between back button and header when there is no warning/error banner in between
- (Mary) Added drop full-width drop shadow below sticky header

## Related Issue

Fixes #975 

## Screenshots
Screenshot 2025-08-06 at 11 41 23
Screenshot 2025-08-06 at 11 41 34

## Acceptance Criteria

Please copy the acceptance criteria from your ticket and paste it here for your reviewer(s)

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

### CODE REVIEW

**Comment by angelathe** [comment]
Note: Did not add the full-width drop shadow since its width is limited by its container. (unless....CSS wizard @mcmcgrath13 ?)

File: containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx [hunk 1]
```diff
@@ -53,17 +53,23 @@ export const FormPageContent = <T,>({
...
+            href={itemHomeRoute}
+            className="action-text display-inline-flex flex-align-center margin-bottom-1"
+          >
+            <ArrowBack aria-hidden={true} className="square-3" />
+            Back to {itemType} management
+          </Link>
+          <div
+            className={
+              banner || formTouched || error
+                ? "minh-5 margin-bottom-1"
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx:69]: do we need the `min-h` (or even the margin) ? that was there to hold space for the banner-to-be

Comment (angelathe) [reply containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx]: Removed both -- could've kept `margin-bottom-1` for consistency, but it makes a pretty marginal difference

**Comment by angelathe** [comment]
Confirmed Ashton said `shadow-2` is fine

**Review by mcmcgrath13 — APPROVED** [review]
🎋

File: containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx (hunk 1 above)
Comment (angelathe) [reply containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx]: Scratch that, adding it back in. Spacing is better with `margin-bottom-1` between banner and save button.
