### PR TITLE
fix: update content to banner for creating program area

### LINKED ISSUE #903: Create program area: update content on warning banner
## Description

When a user is creating a program area (not editing), there should be a warning banner that persists in order to warn them of the 2 steps they need to complete in order to properly save the program area.

Follow the same styling as #900

1. I am creating a program area
2. When I'm on the `Create Program Area` form and begin to go through it, the warning banner explains to me that I need to add a program area name & choose at least 1 condition

Note on accessibility: There are callouts within the form that call out the need to add the program area name and at least 1 condition. 

## Expected Result

Content change. [Figma design in dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer--Aug-2024---Present-?node-id=12577-63243&m=dev)

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority

- [ ] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [X] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Figma File

[Figma file in dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer--Aug-2024---Present-?node-id=12587-35130&m=dev)

### PR DESCRIPTION
**Pull request by angelathe**
# PULL REQUEST

_PR title: Remember to name your PR descriptively and follow [conventional commits](https://cheatsheets.zip/conventional-commits)!_

## Summary

Update content on warning banner when creating program area:
`You have unsaved changes. To create a program area, you must add a program name and at least one condition.`

## Related Issue

Fixes #903 

## Screenshots
Create Program Area (additional content)
Screenshot 2025-08-04 at 12 39 38

Edit Program Area (no additional content)
Screenshot 2025-08-04 at 12 39 49

Create/Edit User (no additional content)
Screenshot 2025-08-04 at 12 40 04

## Acceptance Criteria

1. I am creating a program area
2. When I'm on the Create Program Area form and begin to go through it, the warning banner explains to me that I need to add a program area name & choose at least 1 condition

New content should **not** appear on the `Edit Program Area` page

## Additional Information

N/A

### CODE REVIEW

File: containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx [hunk 1]
```diff
@@ -71,10 +71,15 @@ export const FormPageContent = <T,>({
                 headingLevel="h4"
                 aria-live="polite"
               >
-                You have unsaved changes
+                You have unsaved changes.{" "}
+                {itemType === "program area" && action === "Create" && (
+                  <>
+                    To create a program area, you must add a program name and at
+                    least one condition.
+                  </>
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx:79]: Instead of hardcoding this here, can we plumb it through as a prop? I imagine we're going to want to take advantage of this prop for user as well

Comment (angelathe) [reply containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx:79]: I thought we'd use it for user too but I didn't see any designs for it -- @ashton-skylight can you confirm?

Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx:79]: 👀 

even if we don't use it for user, I'd still lean towards having it be a prop to keep it close to the program creation logic as this component is agnostic to the type of item and action used

Comment (ashton-skylight) [reply containers/ecr-viewer/src/app/components/forms/FormPageContent.tsx:79]: @angelathe If we want to add additional context for the user, the banner could say, "You have unsaved changes. To create a user, you must add an email and select a user type."

File: containers/ecr-viewer/src/app/admin/user/create/page.tsx [hunk 2]
```diff
@@ -13,6 +13,7 @@ const CreateUserPage = async () => {
   await notFoundUnlessAdmin();
 
   const programs = await listProgramAreas();
+  const formTouchedMsg = "To create a user, you must add an email and select a user type.";
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/admin/user/create/page.tsx]: does this need the "you have unsaved changes" as well?

**Review by mcmcgrath13 — APPROVED** [review]
a couple minor comments, but nothing I need to review again before merge

🥇
