### PR TITLE
fix: Add program areas to confirmation modal

### LINKED ISSUE #909: Program management - specify program area(s) in move modal
## Description

When a user moves multiple reportable conditions, these reportable conditions can come from different program areas. 

When there are 2 program areas, the format in the modal should look like: `Program area and program area'
When there are 2+ program areas, the format in the modal should like: 'Program area, program area, and program area'

Can also be done with #908

Reportable conditions will be listed in alphabetical order with a ',' to separate their previously assigned program area. This could look like: 
- Amebiasis, Acute Communicable Diseases
- Echinococcosis, Zoonotic 
- Paratyphi Infection, Enteric
- Scabies, Zoonotic 
- Strongyloidiasis, Zoonotic 

## Expected Result

[Figma file in dev mode](https://www.figma.com/design/zAPyOEYwNtx3f2Y47aoq0G/eCR-Viewer--Aug-2024---Present-?node-id=12577-63243&m=dev)

Separate the program area by`and` when there are 2 program areas 

Separate the program area by ',' when there are 2+ program areas 

## Actual result

_Explain what's happening now when the bug is present. Attach screenshot if applicable_

## Priority

_Provide an estimate for level of impact the bug has today by placing an X in the applicable bracket_

#### Priority

- [X] **Low priority** _The bug does not have to be fixed immediately. High and medium priority bugs should be addressed first._
- [ ] **Medium priority** _Typically, medium-priority bugs do not affect customers directly and therefore can be fixed in the normal course of testing and development._
- [ ] **High priority** _High priority bugs must be addressed immediately. They often affect the app’s functionality and impact customers and their user experience. They must take priority._

## Notes

_Include any additional context or information here that doesn't fit into other parts of the template_

### PR DESCRIPTION
**Pull request by angelathe**
# PULL REQUEST
## Summary

Lists program area(s) when a user moves multiple reportable conditions 

## Related Issue
Fixes #909 

## Screenshots
When moving multiple reportable conditions & reportable conditions come from 1 other program area:
image

When moving multiple reportable conditions & reportable conditions come from 2 program areas:
image

When moving multiple reportable conditions & reportable conditions come from 2+ program areas:
image

## Acceptance Criteria

When a user moves multiple reportable conditions, these reportable conditions can come from different program areas.
- [ ] When there are 2 program areas, the format in the modal should look like: `Program area and program area'
- [ ] When there are 2+ program areas, the format in the modal should like: 'Program area, program area, and program area'

## Additional Information

Anything else the review team should know?

## Checklist

- [ ] If this code affects the other scrum team, have they been notified? (In Slack, as reviewers, etc.)

### CODE REVIEW

File: containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx [hunk 1]
```diff
@@ -464,8 +477,8 @@ const ConfirmationModal = ({
             <div id="confirm-condition-description">
               <p>
                 A condition can only live in one program area. If you add the
-                below conditions to this program area, they will be removed from
-                their current program area.
+                below conditions to this program area, they will be removed
+                {prevProgramAreasStr && <> from {prevProgramAreasStr}</>}.
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx:481]: when wouldn't we have the program area string here?

Comment (angelathe) [reply containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx:481]: I think we always would -- but added for type safety since `categoryConditions.program_area_name` can technically come back `null`. I can remove if you think it's superfluous

File: containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx [hunk 2]
```diff
@@ -430,6 +430,19 @@ const ConfirmationModal = ({
   onConfirm: () => void;
   modalRef: RefObject<ModalRef>;
 }) => {
+  const prevProgramAreas = Array.from(
+    new Set(categoryConditions.map((c) => c.program_area_name)),
+  );
```
Comment (mcmcgrath13) [inline containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx:435]:
```suggestion
  const prevProgramAreas = [
    ...new Set(categoryConditions.map((c) => c.program_area_name)),
  ].sort(stringSort);
```

just for consistency with everywhere else

File: containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx (hunk 1 above)
Comment (mcmcgrath13) [reply containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx:481]: it really ought to be there, otherwise we're in a broken state, so I lean towards asserting that and just changing this to `from {prevProgramAreaStr!}`, but I flipflop, as I don't love adding the `!`

File: containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx [hunk 3]
```diff
@@ -464,8 +472,8 @@ const ConfirmationModal = ({
             <div id="confirm-condition-description">
               <p>
                 A condition can only live in one program area. If you add the
-                below conditions to this program area, they will be removed from
-                their current program area.
+                below conditions to this program area, they will be removed from{" "}
+                {toReadableListString(prevProgramAreas)}.
```
Comment (angelathe) [inline containers/ecr-viewer/src/app/admin/program/ProgramForm.tsx:481]: @mcmcgrath13 Didn't end up needing `prevProgramAreas!` because I had to filter out the falsey values in `prevProgramAreas` anyways to apply the sorting function.

**Review by mcmcgrath13 — APPROVED** [review]
📝
